#!/usr/bin/env python3
import os
import sys
import json
import glob
import tomllib
from typing import List
from pydantic import BaseModel
from google import genai
from google.genai import types


# Define structured output for the LLM-as-a-judge
class EvaluationResult(BaseModel):
    passed: bool
    reasoning: str
    missing_criteria: List[str]


def load_prompt(prompt_name: str) -> str:
    filepath = os.path.join("commands", "prompts", f"{prompt_name}.toml")
    if not os.path.exists(filepath):
        raise FileNotFoundError(f"Prompt template {filepath} not found.")

    with open(filepath, "rb") as f:
        data = tomllib.load(f)
        return data.get("prompt", "")


def run_evaluation():
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        print(
            "❌ Error: GEMINI_API_KEY environment variable is not set.", file=sys.stderr
        )
        print(
            "Please set it to run the golden tests: export GEMINI_API_KEY='your_key'",
            file=sys.stderr,
        )
        sys.exit(1)

    client = genai.Client(api_key=api_key)
    # Using the fast model for evaluation
    model_id = "gemini-2.5-flash"

    dataset_files = glob.glob("tests/golden_datasets/*.json")
    if not dataset_files:
        print("No golden datasets found in tests/golden_datasets/")
        sys.exit(0)

    total_tests = 0
    passed_tests = 0

    print(f"🚀 Starting PromptOps Golden Tests using {model_id}...\n")

    for dataset_file in dataset_files:
        with open(dataset_file, "r", encoding="utf-8") as f:
            dataset = json.load(f)

        prompt_name = dataset.get("prompt_name")
        print(f"📦 Evaluating Prompt: {prompt_name}")

        try:
            raw_prompt_template = load_prompt(prompt_name)
        except FileNotFoundError as e:
            print(f"  ❌ Error: {e}")
            continue

        for test_case in dataset.get("test_cases", []):
            total_tests += 1
            test_name = test_case.get("name")
            input_data = test_case.get("input", "")
            criteria = test_case.get("evaluator_criteria", [])

            print(f"  🧪 Test Case: {test_name}...", end="", flush=True)

            # 1. Hydrate the prompt
            hydrated_prompt = raw_prompt_template.replace("{{args}}", input_data)

            try:
                # 2. Generate the output from the prompt template
                response = client.models.generate_content(
                    model=model_id, contents=hydrated_prompt
                )
                generated_output = response.text

                # 3. Use LLM-as-a-judge to evaluate the generated output against criteria
                judge_prompt = f"""
You are an expert prompt evaluator. You need to evaluate if a generated output meets a specific set of criteria.

Here is the Output generated by an AI:
<output>
{generated_output}
</output>

Here are the criteria that MUST be met:
{json.dumps(criteria, indent=2)}

Analyze the output carefully. If ALL criteria are met, passed is true. If ANY criterion is missing, passed is false, and you must list the missing criteria. Provide reasoning.
"""
                eval_response = client.models.generate_content(
                    model=model_id,
                    contents=judge_prompt,
                    config=types.GenerateContentConfig(
                        response_mime_type="application/json",
                        response_schema=EvaluationResult,
                    ),
                )

                result = EvaluationResult.model_validate_json(eval_response.text)

                if result.passed:
                    print(" ✅ PASS")
                    passed_tests += 1
                else:
                    print(" ❌ FAIL")
                    print(f"     Reasoning: {result.reasoning}")
                    if result.missing_criteria:
                        print(
                            f"     Missing Criteria: {', '.join(result.missing_criteria)}"
                        )

            except Exception as e:
                print(f" ❌ ERROR: API Call Failed - {e}")

    print("\n" + "=" * 40)
    print(f"📊 Golden Test Results: {passed_tests}/{total_tests} Passed")
    print("=" * 40)

    if passed_tests != total_tests:
        sys.exit(1)


if __name__ == "__main__":
    run_evaluation()
