#!/usr/bin/env python3
import glob
import json
import os
import sys

# Add current directory to path so we can import our package
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

try:
    import tomllib
except ImportError:
    import tomli as tomllib

from promptbook import LLMClient


# Define structured output for the LLM-as-a-judge
class EvaluationResult:
    def __init__(self, passed: bool, reasoning: str, missing_criteria: list[str]):
        self.passed = passed
        self.reasoning = reasoning
        self.missing_criteria = missing_criteria


def load_prompt(prompt_name: str) -> dict:
    # Handle both flat and nested directory structures
    filepath = os.path.join("commands", "prompts", f"{prompt_name}.toml")
    if not os.path.exists(filepath):
        # Search recursively if not found in root
        matches = glob.glob(
            os.path.join("commands", "prompts", "**", f"{prompt_name}.toml"),
            recursive=True,
        )
        if matches:
            filepath = matches[0]
        else:
            raise FileNotFoundError(f"Prompt template {prompt_name}.toml not found.")

    with open(filepath, "rb") as f:
        return tomllib.load(f)


def run_evaluation():
    client, model_id = LLMClient.get_client_and_model()
    if not client:
        print(
            "❌ Error: Neither OPENAI_API_KEY nor GEMINI_API_KEY is set (checked env and vault).",
            file=sys.stderr,
        )
        sys.exit(1)

    dataset_files = glob.glob("tests/golden_datasets/*.json")
    if not dataset_files:
        print("No golden datasets found in tests/golden_datasets/")
        sys.exit(0)

    total_tests = 0
    passed_tests = 0

    print(f"🚀 Starting promptbook Golden Tests using {model_id}...\n")

    for dataset_file in dataset_files:
        with open(dataset_file, encoding="utf-8") as f:
            dataset = json.load(f)

        prompt_name = dataset.get("prompt_name")
        print(f"📦 Evaluating Prompt: {prompt_name}")

        try:
            prompt_data = load_prompt(prompt_name)
        except FileNotFoundError as e:
            print(f"  ❌ Error: {e}")
            continue

        for test_case in dataset.get("test_cases", []):
            total_tests += 1
            test_name = test_case.get("name")
            input_data = test_case.get("input", "")
            criteria = test_case.get("evaluator_criteria", [])

            print(f"  🧪 Test Case: {test_name}...", end="", flush=True)

            # 1. Prepare messages based on prompt template
            messages = []

            system_template = prompt_data.get("system_prompt", "")
            user_template = prompt_data.get("user_prompt", "")
            legacy_template = prompt_data.get("prompt", "")

            if system_template:
                messages.append(
                    {
                        "role": "system",
                        "content": system_template.replace("{{args}}", input_data),
                    }
                )

            if user_template:
                messages.append(
                    {
                        "role": "user",
                        "content": user_template.replace("{{args}}", input_data),
                    }
                )
            elif legacy_template:
                messages.append(
                    {
                        "role": "user",
                        "content": legacy_template.replace("{{args}}", input_data),
                    }
                )

            if not messages:
                print(" ❌ Error: No prompt content found.")
                continue

            try:
                # 2. Generate the output from the prompt template
                response = client.chat.completions.create(
                    model=model_id,
                    messages=messages,
                )
                generated_output = response.choices[0].message.content

                # 3. Use LLM-as-a-judge to evaluate the generated output against criteria
                judge_prompt = f"""
You are an expert prompt evaluator. You need to evaluate if a generated output meets a specific set of criteria.

Return a JSON object with the following fields:
- passed: boolean (true if ALL criteria are met)
- reasoning: string (briefly explain why)
- missing_criteria: list of strings (list ANY criteria that were not fully met)

Here is the Output generated by an AI:
<output>
{generated_output}
</output>

Here are the criteria that MUST be met:
{json.dumps(criteria, indent=2)}

Analyze the output carefully. If ALL criteria are met, passed is true. If ANY criterion is missing, passed is false.
"""
                eval_response = client.chat.completions.create(
                    model=model_id,
                    messages=[{"role": "user", "content": judge_prompt}],
                    response_format={"type": "json_object"},
                )

                # Parse JSON and create result object
                raw_result = json.loads(eval_response.choices[0].message.content)
                result = EvaluationResult(
                    passed=raw_result.get("passed", False),
                    reasoning=raw_result.get("reasoning", ""),
                    missing_criteria=raw_result.get("missing_criteria", []),
                )

                if result.passed:
                    print(" ✅ PASS")
                    passed_tests += 1
                else:
                    print(" ❌ FAIL")
                    print(f"     Reasoning: {result.reasoning}")
                    if result.missing_criteria:
                        print(f"     Missing Criteria: {', '.join(result.missing_criteria)}")

            except Exception as e:
                print(f" ❌ ERROR: API Call Failed - {e}")

    print("\n" + "=" * 40)
    print(f"📊 Golden Test Results: {passed_tests}/{total_tests} Passed")
    print("=" * 40)

    if passed_tests != total_tests:
        sys.exit(1)


if __name__ == "__main__":
    run_evaluation()
