#!/usr/bin/env python3
import os
import sys
import json
import glob
import tomllib
from typing import List
from pydantic import BaseModel
from openai import OpenAI
from promptbook.utils import Vault


# Define structured output for the LLM-as-a-judge
class EvaluationResult(BaseModel):
    passed: bool
    reasoning: str
    missing_criteria: List[str]


def load_prompt(prompt_name: str) -> str:
    # Handle both flat and nested directory structures
    filepath = os.path.join("commands", "prompts", f"{prompt_name}.toml")
    if not os.path.exists(filepath):
        # Search recursively if not found in root
        matches = glob.glob(
            os.path.join("commands", "prompts", "**", f"{prompt_name}.toml"),
            recursive=True,
        )
        if matches:
            filepath = matches[0]
        else:
            raise FileNotFoundError(f"Prompt template {prompt_name}.toml not found.")

    with open(filepath, "rb") as f:
        data = tomllib.load(f)
        return data.get("prompt", "")


def get_client_and_model():
    """Returns an OpenAI-compatible client and the target model ID."""
    api_key = os.getenv("OPENAI_API_KEY")
    # Check vault if env var not set
    if not api_key:
        api_key = Vault.get_key("openai")
        
    base_url = os.getenv("OPENAI_BASE_URL")
    model_id = os.getenv("OPENAI_MODEL_NAME", "gpt-4o")

    # Fallback to Gemini if requested or if no OpenAI key is present
    gemini_api_key = os.getenv("GEMINI_API_KEY")
    if not gemini_api_key:
        gemini_api_key = Vault.get_key("gemini")

    if not api_key and gemini_api_key:
        # Use Google's OpenAI-compatible endpoint
        api_key = gemini_api_key
        base_url = "https://generativelanguage.googleapis.com/v1beta/openai/"
        model_id = os.getenv("OPENAI_MODEL_NAME", "gemini-2.0-flash")

    if not api_key:
        print(
            "❌ Error: Neither OPENAI_API_KEY nor GEMINI_API_KEY is set (checked env and vault).",
            file=sys.stderr,
        )
        sys.exit(1)

    client = OpenAI(api_key=api_key, base_url=base_url)
    return client, model_id


def run_evaluation():
    client, model_id = get_client_and_model()

    dataset_files = glob.glob("tests/golden_datasets/*.json")
    if not dataset_files:
        print("No golden datasets found in tests/golden_datasets/")
        sys.exit(0)

    total_tests = 0
    passed_tests = 0

    print(f"🚀 Starting promptbook Golden Tests using {model_id}...\n")

    for dataset_file in dataset_files:
        with open(dataset_file, "r", encoding="utf-8") as f:
            dataset = json.load(f)

        prompt_name = dataset.get("prompt_name")
        print(f"📦 Evaluating Prompt: {prompt_name}")

        try:
            raw_prompt_template = load_prompt(prompt_name)
        except FileNotFoundError as e:
            print(f"  ❌ Error: {e}")
            continue

        for test_case in dataset.get("test_cases", []):
            total_tests += 1
            test_name = test_case.get("name")
            input_data = test_case.get("input", "")
            criteria = test_case.get("evaluator_criteria", [])

            print(f"  🧪 Test Case: {test_name}...", end="", flush=True)

            # 1. Hydrate the prompt (simple replacement for eval)
            hydrated_prompt = raw_prompt_template.replace("{{args}}", input_data)

            try:
                # 2. Generate the output from the prompt template
                response = client.chat.completions.create(
                    model=model_id,
                    messages=[{"role": "user", "content": hydrated_prompt}],
                )
                generated_output = response.choices[0].message.content

                # 3. Use LLM-as-a-judge to evaluate the generated output against criteria
                judge_prompt = f"""
You are an expert prompt evaluator. You need to evaluate if a generated output meets a specific set of criteria.

Return a JSON object with the following fields:
- passed: boolean (true if ALL criteria are met)
- reasoning: string (briefly explain why)
- missing_criteria: list of strings (list ANY criteria that were not fully met)

Here is the Output generated by an AI:
<output>
{generated_output}
</output>

Here are the criteria that MUST be met:
{json.dumps(criteria, indent=2)}

Analyze the output carefully. If ALL criteria are met, passed is true. If ANY criterion is missing, passed is false.
"""
                eval_response = client.chat.completions.create(
                    model=model_id,
                    messages=[{"role": "user", "content": judge_prompt}],
                    response_format={"type": "json_object"},
                )

                # Parse JSON and validate with Pydantic
                raw_result = json.loads(eval_response.choices[0].message.content)
                result = EvaluationResult(**raw_result)

                if result.passed:
                    print(" ✅ PASS")
                    passed_tests += 1
                else:
                    print(" ❌ FAIL")
                    print(f"     Reasoning: {result.reasoning}")
                    if result.missing_criteria:
                        print(
                            f"     Missing Criteria: {', '.join(result.missing_criteria)}"
                        )

            except Exception as e:
                print(f" ❌ ERROR: API Call Failed - {e}")

    print("\n" + "=" * 40)
    print(f"📊 Golden Test Results: {passed_tests}/{total_tests} Passed")
    print("=" * 40)

    if passed_tests != total_tests:
        sys.exit(1)


if __name__ == "__main__":
    run_evaluation()
